# eureka client configs
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    #connect with eureka server
    register-with-eureka: true
    # url for the service to connect to
    service-url:
      # use the env variable if there's one, if not use the default which is localhost...
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
